# Scaffolding generated by Casein v5.1.1.5

module Casein
  class GlobalsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Globals'
  		@globals = Global.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View global'
      @global = Global.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new global'
    	@global = Global.new
    end

    def create
      @global = Global.new global_params
    
      if @global.save
        flash[:notice] = 'Global created'
        redirect_to casein_globals_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new global'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update global'
      
      @global = Global.find params[:id]
    
      if @global.update_attributes global_params
        flash[:notice] = 'Global has been updated'
        redirect_to casein_globals_path
      else
        flash.now[:warning] = 'There were problems when trying to update this global'
        render :action => :show
      end
    end
 
    def destroy
      @global = Global.find params[:id]

      @global.destroy
      flash[:notice] = 'Global has been deleted'
      redirect_to casein_globals_path
    end
  
    private
      
      def global_params
        params.require(:global).permit(:title, :keyword)
      end

  end
end