# Scaffolding generated by Casein v5.1.1.5

module Casein
  class HomepagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Homepages'
  		@homepages = Homepage.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View homepage'
      @homepage = Homepage.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new homepage'
    	@homepage = Homepage.new
    end

    def create
      @homepage = Homepage.new homepage_params
    
      if @homepage.save
        flash[:notice] = 'Homepage created'
        redirect_to casein_homepages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new homepage'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update homepage'
      
      @homepage = Homepage.find params[:id]
    
      if @homepage.update_attributes homepage_params
        flash[:notice] = 'Homepage has been updated'
        redirect_to casein_homepages_path
      else
        flash.now[:warning] = 'There were problems when trying to update this homepage'
        render :action => :show
      end
    end
 
    def destroy
      @homepage = Homepage.find params[:id]

      @homepage.destroy
      flash[:notice] = 'Homepage has been deleted'
      redirect_to casein_homepages_path
    end
  
    private
      
      def homepage_params
        params.require(:homepage).permit(:title)
      end

  end
end