
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: M@shey111

development:
  <<: *default
  database: project_vets


test:
  <<: *default
  database: project_vets_test

staging:
  <<: *default


production:
  <<: *default
  database: project_vets_prod
